@startmindmap
*[#Orange] Аналитика данных
** Сбор и подготовка данных
** Анализ и исследование данных
** Визуализация и отчетность
** Ответы на бизнес-вопросы
** Прогнозирование и моделирование
** Автоматизация процессов
@endmindmap
