@startmindmap
<style>
mindmapDiagram {
  .red {
    BackgroundColor lightcoral
  }
  .blue {
    BackgroundColor lightblue
  }
  .green {
    BackgroundColor lightgreen
  }
}
</style>

*[#lightblue] Аналитика данных
**[#lightcoral] Hard Skills
***[#lightcoral] <&code> Программирование
**** Python (pandas, numpy)
**** R
**** SQL
**** Bash/Shell
***[#lightcoral] <&calculator> Статистика
**** Описательная статистика
**** Проверка гипотез
**** A/B тестирование
**** Регрессионный анализ
***[#lightcoral] <&graph> Визуализация
**** Tableau
**** Power BI
**** Matplotlib/Seaborn
**** Plotly
***[#lightcoral] <&brain> Machine Learning
**** Классификация
**** Кластеризация
**** NLP
**** Рекомендательные системы
***[#lightcoral] <&server> Инфраструктура
**** Базы данных
**** ETL/ELT
**** Docker
**** Git
**[#lightgreen] Soft Skills
***[#lightgreen] <&people> Коммуникация
***[#lightgreen] <&bulb> Критическое мышление
***[#lightgreen] <&check> Решение проблем
***[#lightgreen] <&briefcase> Работа с stakeholders
**[#gold] Доменная экспертиза
***[#gold] <&trend-up> Бизнес-метрики
***[#gold] <&process> Понимание процессов
***[#gold] <&book> Отраслевые знания
@endmindmap
